language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --dev --prefer-source

script:
  - vendor/bin/phpspec run  --format pretty

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
